name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci-angular-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            node_modules
          retention-days: 1

  ci-angular-lint:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Lint
        run: npm run lint

  ci-angular-format-check:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Format check
        run: npm run format:check

  ci-angular-build:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Build
        run: npm run build

  ci-angular-test:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Test
        run: npm run test:ci
