name: CI Angular

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci-angular-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Cache workspace
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
  ci-angular-lint:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          fail-on-cache-miss: true
      - name: Lint
        run: npm run lint

  ci-angular-format-check:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Format check
        run: npm run format:check

  ci-angular-build:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          fail-on-cache-miss: true
      - name: Build
        run: npm run build

  ci-angular-test:
    needs: ci-angular-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          fail-on-cache-miss: true
      - name: Test
        run: npm run test:ci
